export { Home } from "./Home";
export { PageNotFound } from "./PageNotFound";
export { ProductDetail } from "./ProductDetail";
export { ProductList } from "./ProductList";
export { Contact } from "./Contact/Contact";
export { ContactEu } from "./Contact/ContactEu";
export { ContactUs } from "./Contact/ContactUs";
export { ContactOther } from "./Contact/ContactOther";
export { ContactIn } from "./Contact/ContactIn";
